apiVersion: apps/v1
kind: Deployment
metadata:
  name: vegetable-deployment
  namespace: yash-ns
spec:
  replicas: 4
  selector:
    matchLabels:
      app: vegetable-app
  template:
    metadata:
      labels:
        app: vegetable-app
    spec:
      containers:
      - name: vegetable-container
        image: yashwanth1712/vegetable:v1.0.0
        ports:
        - containerPort: 3000
        env:
        - name: MONGODB_URI
          valueFrom:
            configMapKeyRef:
              name: vegetable-config
              key: MONGODB_URI
